spring:
  application:
    name: zuul-server
server:
  port : 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://18.208.151.67:8761/eureka/
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://18.208.151.67:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://18.208.151.67:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://18.208.151.67:1003
    cart:
      path: /cart/**
      url: http://18.208.151.67:1004/api/v1
    shoe-service:
      path: /shoeapi/**
      serviceId: shoe-client
    offer-service:
      path: /offerapi/**
      serviceId: offers-client
    cart-service:
      path: /cartapi/**
      serviceId: cart-client